sudo: required
services:
  - docker

before_install:
  - docker build -t lukrebs/docker-react -f Dockerfile.dev .

script:
  - docker run lukrebs/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-app"
  env: "DockerApp-env"
  bucket_name: "elasticbeanstalk-us-east-2-110648490027"
  bucket_path: "docker-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
